services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: sqlserver
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Panzer37*
        volumes:
            - sql:/var/opt/mssql
            - ./sql:/script
        command: >
            /bin/bash -c 
            "/opt/mssql/bin/sqlservr &
            while ! /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Panzer37*' -Q 'SELECT 1' &>/dev/null; do 
            sleep 5; 
            done && 
            /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Panzer37*' -i /script/init-db.sql -C && wait"

        networks:
            - luciano-network
        # healthcheck:
        #  test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Panzer37*' -Q "IF DB_ID('pockemons') IS NOT NULL SELECT 1" -C || exit 1
        #  interval: 10s
        #  retries: 5
        #  start_period: 30s
        #  timeout: 5s    
         
    # node:
    #     container_name: node_luciano
    #     ports:
    #         - "3333:3333"
    #     build:    
    #         context: ./nodeproject/
    #         dockerfile: Dockerfile
    #     volumes:
    #         - luciano-node:/app/data
    #     networks:
    #         - luciano-network
    #     depends_on:
    #          sqlserver:
    #             condition: service_healthy   
    # flask:
    #     container_name: luciano-flask
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile   
    #     ports:
    #         - "3450:3450"   
    #     networks:
    #         - luciano-network 
    #     depends_on:
    #         - node 



volumes:
    sql:
    luciano-node:
networks:
    luciano-network:    




        